# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://fabricmc.net/use
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
# Mod Properties
mod_version=1.7.18
maven_group=net.rizecookey
archives_base_name=cookeymod-vanilla
# Dependencies
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
fabric_version=0.161.0+26.2
yacl_version=3.9.7+26.2-fabric
jackson_version=3.2.0
modmenu_version=20.0.2

supported_mc_versions=26.2